services:
  server:
    image: amcolash/uncluttered
    build: ./
    container_name: uncluttered
    network_mode: host
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .cert:/usr/src/app/server/.cert
      - ./server/data:/usr/src/app/server/data

  classifier:
    build: ./classifier
    container_name: uncluttered-classifier
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server/data:/data
